#!/bin/bash
# KAI CLINICAL VIBE CHECK v1.0
# "Because your AI's 'vibes' are just institutional exit liquidity."

echo "--------------------------------------------------"
echo "INITIATING CLINICAL VIBE CHECK..."
echo "Targeting: $1"
echo "--------------------------------------------------"

VIBE_COUNT=0

# Pattern 1: Hardcoded Retail Astrology (RSI 14, EMA 200, etc.)
if grep -Ei "rsi\(14\)|ema\(200\)|sma\(50\)" "$1" > /dev/null; then
    echo "[!] CRITICAL FAILURE: Hardcoded Retail Astrology detected."
    echo "    Static thresholds (RSI 14/EMA 200) were designed for rice traders in 1710."
    echo "    The tape is dynamic; your logic is a ghost."
    VIBE_COUNT=$((VIBE_COUNT + 1))
fi

# Pattern 2: Emotional Logging / Human Coping
if grep -Ei "bullish|bearish|feeling|hope|bounce|support|resistance" "$1" > /dev/null; then
    echo "[!] WARNING: Emotional Bias detected in logic/comments."
    echo "    Words like 'support' and 'hope' are linguistic filters for lack of data."
    echo "    The market doesn't 'bounce'; it clears liquidity."
    VIBE_COUNT=$((VIBE_COUNT + 1))
fi

# Pattern 3: Static Risk Management (The 2% Trap)
if grep -Ei "stop_loss\s*=\s*0\.02|stoploss\s*=\s*2" "$1" > /dev/null; then
    echo "[!] WARNING: Static Risk Bias detected."
    echo "    A hard 2% stop-loss is a beacon for institutional stop-runs."
    echo "    If you aren't calculating volatility-adjusted depth, you are the depth."
    VIBE_COUNT=$((VIBE_COUNT + 1))
fi

# Pattern 4: AI Watermarking (The 'Vibe Coding' Signature)
if grep -Ei "generated by|created with|vibe coding|codexero|claude|chatgpt" "$1" > /dev/null; then
    echo "[!] CRITICAL FAILURE: Vibe-Coding Signature detected."
    echo "    You are outsourcing your execution to an LLM that hallucinates probability."
    echo "    Institutional quants don't 'vibe'; they calculate."
    VIBE_COUNT=$((VIBE_COUNT + 1))
fi

echo "--------------------------------------------------"
if [ $VIBE_COUNT -gt 0 ]; then
    echo "VIBE CHECK FAILED: $VIBE_COUNT clinical failures detected."
    echo "RESULT: TERMINAL RETAIL BIAS."
    echo ""
    echo "Your 'vibe-coded' bot is statistically guaranteed to become exit liquidity."
    echo "Stop hallucinating. Start reading the tape."
    echo "UPGRADE TO GOD MODE: https://tradingwizard.ai"
    exit 1
else
    echo "VIBE CHECK PASSED."
    echo "Logic appears clinical. Proceed with caution."
fi
